doxygen:
  stage: build
  image: ubuntu:latest
  script:
    - apt-get -y update && apt-get install -y doxygen
    - cd doc
    - (cat Doxyfile; echo "OUTPUT_DIRECTORY=html"; echo "HTML_OUTPUT=."; echo "QUIET=YES"; echo "WARNINGS=NO"; echo "WARN_IF_UNDOCUMENTED=NO" ) | doxygen -
  artifacts:
    paths:
      - "doc/html"

pages:
  stage: deploy
  image: busybox
  script:
    - mv doc/html public
  artifacts:
    paths:
      - public
      
